In [1]:
import pandas as pd
import glob 
import os

# Task 1: Merge datasets

In [2]:
def extractFiles(path): 

    all_files = glob.glob(os.path.join(path , "*.csv"))
    return all_files

In [3]:
path = r'C:\Users\Rahul Nagarajan\Desktop\MS Project\Untitled Folder\Test_Data' 
all_files = extractFiles(path)

In [4]:
def mergeDF(all_files):
    li = []

    for filename in all_files:
        df = pd.read_csv(filename, skiprows=1, index_col=None, header=0)
        #Epoc X has 14 channels and sampling rate of 128hz
        df = df.iloc[:, [4,5,6,7,8,9,10,11,12,13,14,15,16,17]]
        li.append(df)
#     df = pd.concat(li, axis=0, ignore_index=True)
    return df

In [5]:
df = mergeDF(all_files)

In [6]:
df

,EEG.AF3,EEG.F7,EEG.F3,EEG.FC5,EEG.T7,EEG.P7,EEG.O1,EEG.O2,EEG.P8,EEG.T8,EEG.FC6,EEG.F4,EEG.F8,EEG.AF4
0,4311.282227,4313.846191,4305.769043,4306.025879,4281.282227,4282.307617,4292.692383,4315.897461,4301.025879,4285.384766,4467.307617,4390.512695,4399.871582,4441.794922
1,4317.051270,4319.743652,4319.487305,4312.179688,4290.128418,4287.948730,4305.769043,4327.948730,4306.922852,4293.846191,4479.102539,4392.563965,4420.897461,4450.897461
2,4302.563965,4310.769043,4307.436035,4305.641113,4290.384766,4290.769043,4302.307617,4317.436035,4293.077148,4280.384766,4464.871582,4380.769043,4408.333496,4435.000000
3,4291.153809,4294.230957,4287.436035,4295.128418,4280.769043,4290.769043,4295.641113,4307.563965,4288.077148,4268.717773,4454.615234,4371.153809,4390.512695,4421.666504
4,4296.922852,4293.589844,4290.256348,4292.436035,4278.205078,4286.153809,4299.615234,4313.205078,4297.948730,4273.461426,4463.974121,4373.717773,4394.102539,4428.205078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7812,4314.871582,4342.179688,4310.000000,4329.102539,4302.948730,4256.153809,4286.666504,4303.205078,4293.974121,4266.410156,4476.153809,4448.333496,4386.410156,4432.307617
7813,4310.256348,4341.153809,4309.487305,4327.948730,4301.922852,4259.358887,4295.128418,4312.563965,4300.897461,4271.922852,4480.512695,4451.282227,4383.846191,4435.256348
7814,4293.205078,4318.846191,4296.410156,4311.410156,4295.000000,4255.641113,4294.358887,4308.717773,4299.743652,4274.871582,4472.179688,4449.358887,4369.102539,4426.538574
7815,4284.230957,4309.615234,4287.436035,4300.897461,4286.666504,4252.307617,4284.743652,4297.436035,4295.384766,4267.436035,4462.563965,4438.974121,4356.153809,4412.307617
7816,4281.153809,4306.153809,4280.128418,4302.563965,4280.769043,4253.333496,4287.307617,4297.692383,4288.205078,4254.615234,4453.589844,4433.461426,4338.974121,4403.589844

In [7]:
#Saving the merged dataframe as a csv file 
df.to_csv('file.csv')

# Task 2: Feature Extraction

In [8]:
import eeglib

In [9]:
#Preprocessing the data with a highpass filter of 1hz and lowpass filter of 50hz
helper = eeglib.helpers.CSVHelper('file.csv', sampleRate=128, normalize=True, highpass=1, lowpass=50)
wrapper = eeglib.wrapper.Wrapper(helper)

In [10]:
#Extracting Petrosian Fractal Dimension for each window in the dataset 
def featureExtraction(wrapper):
    wrapper.addFeature.PFD()
    data = wrapper.getAllFeatures()
    return data

In [11]:
data = featureExtraction(wrapper)

In [12]:
data

,PFD(){}_0,PFD(){}_1,PFD(){}_2,PFD(){}_3,PFD(){}_4,PFD(){}_5,PFD(){}_6,PFD(){}_7,PFD(){}_8,PFD(){}_9,PFD(){}_10,PFD(){}_11,PFD(){}_12,PFD(){}_13,PFD(){}_14
window_id,,,,,,,,,,,,,,,
0,1.001286,1.033205,1.035551,1.033205,1.032027,1.033793,1.034966,1.031436,1.035551,1.035551,1.035551,1.033205,1.032616,1.033205,1.030845
1,1.000643,1.032616,1.034966,1.033793,1.033793,1.037301,1.031436,1.033793,1.034380,1.034380,1.033205,1.033205,1.034380,1.032027,1.032616
2,1.000643,1.032616,1.030252,1.030252,1.032616,1.036135,1.033793,1.037301,1.036135,1.032027,1.035551,1.033793,1.031436,1.029659,1.030252
3,1.001286,1.030845,1.035551,1.032027,1.034380,1.036719,1.033793,1.030845,1.036135,1.036719,1.035551,1.032616,1.034380,1.030845,1.033205
4,1.000643,1.033793,1.034380,1.036719,1.036719,1.036719,1.036719,1.039622,1.040201,1.036719,1.034380,1.036719,1.037883,1.033205,1.036719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1.043079,1.033793,1.034380,1.034966,1.034966,1.034966,1.034966,1.036135,1.031436,1.037301,1.036135,1.038464,1.034966,1.034380,1.036135
57,1.043079,1.033793,1.038464,1.036719,1.039622,1.037301,1.034380,1.036135,1.036719,1.035551,1.036719,1.036719,1.035551,1.036719,1.037883
58,1.043079,1.034380,1.035551,1.034380,1.037883,1.037883,1.033793,1.038464,1.037883,1.035551,1.034380,1.035551,1.035551,1.037883,1.035551
59,1.043079,1.024277,1.024879,1.024879,1.024879,1.036135,1.036135,1.037301,1.034966,1.032616,1.032616,1.032616,1.031436,1.025480,1.026679
60,1.043652,1.032616,1.033205,1.034380,1.033205,1.031436,1.036135,1.032616,1.033793,1.034966,1.033793,1.037301,1.032616,1.033793,1.033793

In [13]:
data.shape

(61, 15)

In [14]:
#One dataset after PFD feature extraction has 61 rows and 15 columns

# Task 3: Label the dataset

In [15]:
data.mean()

PFD(){}_0     1.038517
PFD(){}_1     1.034265
PFD(){}_2     1.034688
PFD(){}_3     1.034054
PFD(){}_4     1.034870
PFD(){}_5     1.035970
PFD(){}_6     1.035939
PFD(){}_7     1.035429
PFD(){}_8     1.035172
PFD(){}_9     1.034865
PFD(){}_10    1.035038
PFD(){}_11    1.035239
PFD(){}_12    1.034710
PFD(){}_13    1.034161
PFD(){}_14    1.034258
dtype: float64

In [16]:
data_copy = data.assign(**data.mean())

In [17]:
data_copy = data_copy.head(1)

In [18]:
dtest = data_copy.iloc[0]

In [19]:
data_copy

,PFD(){}_0,PFD(){}_1,PFD(){}_2,PFD(){}_3,PFD(){}_4,PFD(){}_5,PFD(){}_6,PFD(){}_7,PFD(){}_8,PFD(){}_9,PFD(){}_10,PFD(){}_11,PFD(){}_12,PFD(){}_13,PFD(){}_14
window_id,,,,,,,,,,,,,,,
0,1.038517,1.034265,1.034688,1.034054,1.03487,1.03597,1.035939,1.035429,1.035172,1.034865,1.035038,1.035239,1.03471,1.034161,1.034258

In [20]:
data_copy['Authenticated']='True'

In [21]:
data_copy

,PFD(){}_0,PFD(){}_1,PFD(){}_2,PFD(){}_3,PFD(){}_4,PFD(){}_5,PFD(){}_6,PFD(){}_7,PFD(){}_8,PFD(){}_9,PFD(){}_10,PFD(){}_11,PFD(){}_12,PFD(){}_13,PFD(){}_14,Authenticated
window_id,,,,,,,,,,,,,,,,
0,1.038517,1.034265,1.034688,1.034054,1.03487,1.03597,1.035939,1.035429,1.035172,1.034865,1.035038,1.035239,1.03471,1.034161,1.034258,True

In [22]:
labels = ({'True':1,'False':0})
df_encoded = data_copy.replace(labels)

In [23]:
df_encoded

,PFD(){}_0,PFD(){}_1,PFD(){}_2,PFD(){}_3,PFD(){}_4,PFD(){}_5,PFD(){}_6,PFD(){}_7,PFD(){}_8,PFD(){}_9,PFD(){}_10,PFD(){}_11,PFD(){}_12,PFD(){}_13,PFD(){}_14,Authenticated
window_id,,,,,,,,,,,,,,,,
0,1.038517,1.034265,1.034688,1.034054,1.03487,1.03597,1.035939,1.035429,1.035172,1.034865,1.035038,1.035239,1.03471,1.034161,1.034258,1

In [24]:
x = df_encoded.drop('Authenticated', axis=1)

In [25]:
y= df_encoded.loc[:,'Authenticated'].values

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
from tensorflow.keras.utils import to_categorical
y = to_categorical(y)

In [27]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
y

array([[0., 1.]], dtype=float32)